FROM apache/zeppelin:0.10.1
ENV FLINK_VERSION=1.16.0
ENV SCALA_VERSION=2.12
USER root
RUN mkdir /opt/flink
ADD https://archive.apache.org/dist/flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-scala_2.12.tgz flink-scala.tgz
ADD https://repo1.maven.org/maven2/org/apache/flink/flink-table-api-scala-bridge_${SCALA_VERSION}/$FLINK_VERSION/flink-table-api-scala-bridge_${SCALA_VERSION}-$FLINK_VERSION.jar flink-table-api-scala-bridge_${SCALA_VERSION}-$FLINK_VERSION.jar
RUN tar xzf flink-scala.tgz --directory /opt/flink --strip-components 1 && rm -rf flink-scala.tgz
RUN cp /opt/flink/opt/flink-sql-client-${FLINK_VERSION}.jar /opt/flink/lib/flink-sql-client-${FLINK_VERSION}.jar
RUN cp /opt/flink/opt/flink-table-planner_2.12-${FLINK_VERSION}.jar /opt/flink/lib/flink-table-planner_2.12-${FLINK_VERSION}.jar
RUN cp /opt/flink/lib/flink-table-planner-loader-${FLINK_VERSION}.jar /opt/flink/opt/flink-table-planner-loader-${FLINK_VERSION}.jar
RUN cp flink-table-api-scala-bridge_${SCALA_VERSION}-$FLINK_VERSION.jar /opt/flink/lib/flink-table-api-scala-bridge_${SCALA_VERSION}-$FLINK_VERSION.jar