FROM apache/zeppelin:0.10.1
ENV FLINK_VERSION=1.16.0
USER root
RUN mkdir /opt/flink
RUN wget --no-verbose -O flink-scala.tgz "https://archive.apache.org/dist/flink/flink-${FLINK_VERSION}/flink-${FLINK_VERSION}-bin-scala_2.12.tgz" \
    && tar xzf flink-scala.tgz --directory /opt/flink --strip-components 1 \
    && rm -rf flink-scala.tgz